services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_ROOT_PASSWORD: theFam
      POSTGRES_DATABASE: skull
      POSTGRES_USER: theFam
      POSTGRES_PASSWORD: theFam
    volumes:
      - db-data:/var/lib/mysql
    ports:
      - "5432:5432"

volumes:
  db-data:
